blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/BuunGroup-Packages/npm-precast-icons#readme
    about: Please read the documentation before opening an issue
  - name: Discussions
    url: https://github.com/BuunGroup-Packages/npm-precast-icons/discussions
    about: Ask questions and discuss ideas with the community
